// <auto-generated />
using System;
using FriendlyMeter.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FriendlyMeter.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("FriendlyMeter.Shared.Models.Flat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FlatTariffId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RenterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlatTariffId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RenterId");

                    b.ToTable("Flats");
                });

            modelBuilder.Entity("FriendlyMeter.Shared.Models.Metrics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ColdWaterPriceAtSubmission")
                        .HasColumnType("TEXT");

                    b.Property<int>("ColdWaterValue")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ElectricityPhase1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ElectricityPhase2")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ElectricityPhase3")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ElectricityPriceAtSubmissionPhase1")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ElectricityPriceAtSubmissionPhase2")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ElectricityPriceAtSubmissionPhase3")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlatId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HotWaterPriceAtSubmission")
                        .HasColumnType("TEXT");

                    b.Property<int>("HotWaterValue")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SeweragePriceAtSubmission")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlatId");

                    b.ToTable("Metrics");
                });

            modelBuilder.Entity("FriendlyMeter.Shared.Models.Tariff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ColdWaterPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int>("ElectricityPhasesCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ElectricityPricePhase1")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ElectricityPricePhase2")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ElectricityPricePhase3")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HotWaterPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SeweragePrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Tariffs");
                });

            modelBuilder.Entity("FriendlyMeter.Shared.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FriendlyMeter.Shared.Models.Flat", b =>
                {
                    b.HasOne("FriendlyMeter.Shared.Models.Tariff", "FlatTariff")
                        .WithMany()
                        .HasForeignKey("FlatTariffId");

                    b.HasOne("FriendlyMeter.Shared.Models.User", "Owner")
                        .WithMany("OwnFlats")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FriendlyMeter.Shared.Models.User", "Renter")
                        .WithMany("RentFlats")
                        .HasForeignKey("RenterId");

                    b.Navigation("FlatTariff");

                    b.Navigation("Owner");

                    b.Navigation("Renter");
                });

            modelBuilder.Entity("FriendlyMeter.Shared.Models.Metrics", b =>
                {
                    b.HasOne("FriendlyMeter.Shared.Models.Flat", null)
                        .WithMany("Metrics")
                        .HasForeignKey("FlatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FriendlyMeter.Shared.Models.Tariff", b =>
                {
                    b.HasOne("FriendlyMeter.Shared.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("FriendlyMeter.Shared.Models.Flat", b =>
                {
                    b.Navigation("Metrics");
                });

            modelBuilder.Entity("FriendlyMeter.Shared.Models.User", b =>
                {
                    b.Navigation("OwnFlats");

                    b.Navigation("RentFlats");
                });
#pragma warning restore 612, 618
        }
    }
}
